# Generated by Django 2.2 on 2019-05-09 17:33

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20190509_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
    ]
