# Generated by Django 2.2 on 2019-05-09 17:35

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='state',
            field=localflavor.us.models.USStateField(default='AL', max_length=2),
        ),
    ]
